env: "local"
app_name: "faraway-server"
shutdown_timeout: 5s

logger:
  level: "debug" # Use debug for local development

tcp:
  addr: ":8080" # Port for the server to listen on
  pow_difficulty: 15 # Must match client expectations for PoW
  enable_tls: false # Set to true and configure cert/key files if needed
  # cert_file: "path/to/server.crt" # Uncomment and set path if TLS enabled
  # key_file: "path/to/server.key"  # Uncomment and set path if TLS enabled
  read_timeout: 10s # Increased read timeout slightly
  write_timeout: 10s
  handler_timeout: 20s # Timeout for the entire handler logic per connection